In [1]:
import pandas as pd
import requests
pd.set_option('max_columns', 32)

In [2]:
seasons=pd.read_html("https://www.basketball-reference.com/leagues/NBA_stats_per_game.html")[0]

In [3]:
seasons.columns = [i[1] for i in seasons.columns]

In [4]:
seasons

,Rk,Season,Lg,Age,Ht,Wt,G,MP,FG,FGA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,FG%,3P%,FT%,Pace,eFG%,TOV%,ORB%,FT/FGA,ORtg
0,1,2019-20,NBA,26.0,6-6,216,971,241.7,40.8,88.8,12.1,33.9,17.7,22.9,10.1,34.7,44.9,24.3,7.7,4.9,14.5,20.6,111.4,.460,.357,.771,100.2,.528,12.8,22.6,.199,110.4
1,2,2018-19,NBA,26.3,6-6,217,1230,241.6,41.1,89.2,11.4,32.0,17.7,23.1,10.3,34.8,45.2,24.6,7.6,5.0,14.1,20.9,111.2,.461,.355,.766,100.0,.524,12.4,22.9,.198,110.4
2,3,2017-18,NBA,26.4,6-7,219,1230,241.4,39.6,86.1,10.5,29.0,16.6,21.7,9.7,33.8,43.5,23.2,7.7,4.8,14.3,19.9,106.3,.460,.362,.767,97.3,.521,13.0,22.3,.193,108.6
3,4,2016-17,NBA,26.6,6-7,220,1230,241.6,39.0,85.4,9.7,27.0,17.8,23.1,10.1,33.4,43.5,22.6,7.7,4.7,14.0,19.9,105.6,.457,.358,.772,96.4,.514,12.7,23.3,.209,108.8
4,5,2015-16,NBA,26.7,6-7,221,1230,241.8,38.2,84.6,8.5,24.1,17.7,23.4,10.4,33.3,43.8,22.3,7.8,5.0,14.4,20.3,102.7,.452,.354,.757,95.8,.502,13.2,23.8,.209,106.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,70,1950-51,NBA,NaN,NaN,NaN,354,NaN,29.8,83.6,NaN,NaN,24.5,33.4,NaN,NaN,49.5,21.0,NaN,NaN,NaN,27.0,84.1,.357,NaN,.733,NaN,.357,NaN,NaN,.293,NaN
76,71,1949-50,NBA,NaN,NaN,NaN,561,NaN,28.2,83.1,NaN,NaN,23.6,33.0,NaN,NaN,NaN,19.6,NaN,NaN,NaN,27.0,80.0,.340,NaN,.714,NaN,.340,NaN,NaN,.284,NaN
77,72,1948-49,BAA,NaN,NaN,NaN,360,NaN,29.0,88.7,NaN,NaN,22.0,31.3,NaN,NaN,NaN,18.6,NaN,NaN,NaN,25.6,80.0,.327,NaN,.703,NaN,.327,NaN,NaN,.248,NaN
78,73,1947-48,BAA,NaN,NaN,NaN,192,NaN,27.2,96.0,NaN,NaN,18.2,27.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,22.2,72.7,.284,NaN,.675,NaN,.284,NaN,NaN,.190,NaN
79,74,1946-47,BAA,NaN,NaN,NaN,331,NaN,25.9,92.9,NaN,NaN,15.9,24.8,NaN,NaN,NaN,6.9,NaN,NaN,NaN,20.8,67.8,.279,NaN,.641,NaN,.279,NaN,NaN,.171,NaN

In [5]:
seasons_3 = seasons.loc[:,["Rk","Season","3P","3PA","PTS","3P%"]]
seasons_3

    Rk   Season    3P   3PA    PTS   3P%
0    1  2019-20  12.1  33.9  111.4  .357
1    2  2018-19  11.4  32.0  111.2  .355
2    3  2017-18  10.5  29.0  106.3  .362
3    4  2016-17   9.7  27.0  105.6  .358
4    5  2015-16   8.5  24.1  102.7  .354
..  ..      ...   ...   ...    ...   ...
75  70  1950-51   NaN   NaN   84.1   NaN
76  71  1949-50   NaN   NaN   80.0   NaN
77  72  1948-49   NaN   NaN   80.0   NaN
78  73  1947-48   NaN   NaN   72.7   NaN
79  74  1946-47   NaN   NaN   67.8   NaN

[80 rows x 6 columns]

In [6]:
seasons_3 = seasons_3.dropna(subset=["3P"]).dropna(subset=["Rk"])

In [7]:
cleaningtable=seasons_3["Rk"]!="Rk"
seasons_3=seasons_3.loc[cleaningtable,:]

In [8]:
seasons_3.dtypes

Rk        object
Season    object
3P        object
3PA       object
PTS       object
3P%       object
dtype: object

In [12]:
seasons_3["Rk"]=seasons_3["Rk"].astype(int)
seasons_3["Season"]=seasons_3["Season"].astype(str)
seasons_3["3P"]=seasons_3["3P"].astype(float)
seasons_3["3PA"]=seasons_3["3PA"].astype(float)
seasons_3["PTS"]=seasons_3["PTS"].astype(float)
seasons_3["3P%"]=seasons_3["3P%"].astype(float)

In [13]:
seasons_3.dtypes

Rk          int32
Season     object
3P        float64
3PA       float64
PTS       float64
3P%       float64
dtype: object