# NBA Data Gathering

In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import sqlalchemy as db
import os

## Data Gathering

### Nba Stats per Season (Web Scrapping)

In [9]:
url = "https://www.basketball-reference.com/leagues/NBA_stats_per_game.html"
response = requests.get(url)
soup = BeautifulSoup(response.content)
table = soup.find_all("table", attrs={"id":"stats"})[0]

In [10]:
headers = [header.text.strip() for header in table.find_all('th',attrs={"scope":"col"})][1:]
headers

['Season',
 'Lg',
 'Age',
 'Ht',
 'Wt',
 'G',
 'MP',
 'FG',
 'FGA',
 '3P',
 '3PA',
 'FT',
 'FTA',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'FG%',
 '3P%',
 'FT%',
 'Pace',
 'eFG%',
 'TOV%',
 'ORB%',
 'FT/FGA',
 'ORtg']

In [11]:
data = [data.text.strip() for data in table.find_all('td')]
data

['2019-20',
 'NBA',
 '26.0',
 '6-6',
 '216',
 '971',
 '241.7',
 '40.8',
 '88.8',
 '12.1',
 '33.9',
 '17.7',
 '22.9',
 '10.1',
 '34.7',
 '44.9',
 '24.3',
 '7.7',
 '4.9',
 '14.5',
 '20.6',
 '111.4',
 '.460',
 '.357',
 '.771',
 '100.2',
 '.528',
 '12.8',
 '22.6',
 '.199',
 '110.4',
 '2018-19',
 'NBA',
 '26.3',
 '6-6',
 '217',
 '1230',
 '241.6',
 '41.1',
 '89.2',
 '11.4',
 '32.0',
 '17.7',
 '23.1',
 '10.3',
 '34.8',
 '45.2',
 '24.6',
 '7.6',
 '5.0',
 '14.1',
 '20.9',
 '111.2',
 '.461',
 '.355',
 '.766',
 '100.0',
 '.524',
 '12.4',
 '22.9',
 '.198',
 '110.4',
 '2017-18',
 'NBA',
 '26.4',
 '6-7',
 '219',
 '1230',
 '241.4',
 '39.6',
 '86.1',
 '10.5',
 '29.0',
 '16.6',
 '21.7',
 '9.7',
 '33.8',
 '43.5',
 '23.2',
 '7.7',
 '4.8',
 '14.3',
 '19.9',
 '106.3',
 '.460',
 '.362',
 '.767',
 '97.3',
 '.521',
 '13.0',
 '22.3',
 '.193',
 '108.6',
 '2016-17',
 'NBA',
 '26.6',
 '6-7',
 '220',
 '1230',
 '241.6',
 '39.0',
 '85.4',
 '9.7',
 '27.0',
 '17.8',
 '23.1',
 '10.1',
 '33.4',
 '43.5',
 '22.6',
 '7.7',
 '4.7',
 '14.0',
 '19.9',
 '105.6',
 '.457',
 '.358',
 '.772',
 '96.4',
 '.514',
 '12.7',
 '23.3',
 '.209',
 '108.8',
 '2015-16',
 'NBA',
 '26.7',
 '6-7',
 '221',
 '1230',
 '241.8',
 '38.2',
 '84.6',
 '8.5',
 '24.1',
 '17.7',
 '23.4',
 '10.4',
 '33.3',
 '43.8',
 '22.3',
 '7.8',
 '5.0',
 '14.4',
 '20.3',
 '102.7',
 '.452',
 '.354',
 '.757',
 '95.8',
 '.502',
 '13.2',
 '23.8',
 '.209',
 '106.4',
 '2014-15',
 'NBA',
 '26.7',
 '6-7',
 '222',
 '1230',
 '242.0',
 '37.5',
 '83.6',
 '7.8',
 '22.4',
 '17.1',
 '22.8',
 '10.9',
 '32.4',
 '43.3',
 '22.0',
 '7.7',
 '4.8',
 '14.4',
 '20.2',
 '100.0',
 '.449',
 '.350',
 '.750',
 '93.9',
 '.496',
 '13.3',
 '25.1',
 '.205',
 '105.6',
 '2013-14',
 'NBA',
 '26.5',
 '6-7',
 '223',
 '1230',
 '242.0',
 '37.7',
 '83.0',
 '7.7',
 '21.5',
 '17.8',
 '23.6',
 '10.9',
 '31.8',
 '42.7',
 '22.0',
 '7.7',
 '4.7',
 '14.6',
 '20.7',
 '101.0',
 '.454',
 '.360',
 '.756',
 '93.9',
 '.501',
 '13.6',
 '25.5',
 '.215',
 '106.6',
 '2012-13',
 'NBA',
 '26.7',
 '6-7',
 '223',
 '1229',
 '241.9',
 '37.1',
 '82.0',
 '7.2',
 '20.0',
 '16.7',
 '22.2',
 '11.2',
 '31.0',
 '42.1',
 '22.1',
 '7.8',
 '5.1',
 '14.6',
 '19.8',
 '98.1',
 '.453',
 '.359',
 '.753',
 '92.0',
 '.496',
 '13.7',
 '26.5',
 '.204',
 '105.8',
 '2011-12',
 'NBA',
 '26.6',
 '6-7',
 '223',
 '990',
 '241.9',
 '36.5',
 '81.4',
 '6.4',
 '18.4',
 '16.9',
 '22.5',
 '11.4',
 '30.8',
 '42.2',
 '21.0',
 '7.7',
 '5.1',
 '14.6',
 '19.6',
 '96.3',
 '.448',
 '.349',
 '.752',
 '91.3',
 '.487',
 '13.8',
 '27.0',
 '.208',
 '104.6',
 '2010-11',
 'NBA',
 '26.6',
 '6-7',
 '223',
 '1230',
 '241.9',
 '37.2',
 '81.2',
 '6.5',
 '18.0',
 '18.6',
 '24.4',
 '10.9',
 '30.5',
 '41.4',
 '21.5',
 '7.3',
 '4.9',
 '14.3',
 '20.7',
 '99.6',
 '.459',
 '.358',
 '.763',
 '92.1',
 '.498',
 '13.4',
 '26.4',
 '.229',
 '107.3',
 '2009-10',
 'NBA',
 '26.6',
 '6-7',
 '222',
 '1230',
 '241.7',
 '37.7',
 '81.7',
 '6.4',
 '18.1',
 '18.6',
 '24.5',
 '11.0',
 '30.8',
 '41.7',
 '21.2',
 '7.2',
 '4.9',
 '14.2',
 '20.9',
 '100.4',
 '.461',
 '.355',
 '.759',
 '92.7',
 '.501',
 '13.3',
 '26.3',
 '.228',
 '107.6',
 '2008-09',
 'NBA',
 '26.6',
 '6-7',
 '221',
 '1230',
 '241.7',
 '37.1',
 '80.9',
 '6.6',
 '18.1',
 '19.1',
 '24.7',
 '11.0',
 '30.3',
 '41.3',
 '21.0',
 '7.3',
 '4.8',
 '14.0',
 '21.0',
 '100.0',
 '.459',
 '.367',
 '.771',
 '91.7',
 '.500',
 '13.3',
 '26.7',
 '.236',
 '108.3',
 '2007-08',
 'NBA',
 '26.8',
 '6-7',
 '220',
 '1230',
 '241.5',
 '37.3',
 '81.5',
 '6.6',
 '18.1',
 '18.8',
 '24.9',
 '11.2',
 '30.8',
 '42.0',
 '21.8',
 '7.3',
 '4.7',
 '14.1',
 '21.0',
 '99.9',
 '.457',
 '.362',
 '.755',
 '92.4',
 '.497',
 '13.2',
 '26.7',
 '.231',
 '107.5',
 '2006-07',
 'NBA',
 '26.6',
 '6-7',
 '219',
 '1230',
 '242.2',
 '36.5',
 '79.7',
 '6.1',
 '16.9',
 '19.6',
 '26.1',
 '11.1',
 '29.9',
 '41.1',
 '21.3',
 '7.2',
 '4.6',
 '15.1',
 '22.2',
 '98.7',
 '.458',
 '.358',
 '.752',
 '91.9',
 '.496',
 '14.2',
 '27.1',
 '.246',
 '106.5',
 '2005-06',
 'NBA',
 '26.5',
 '6-7',
 '220',
 '1230',
 '242.1',
 '35.8',
 '79.0',
 '5.7',
 '16.0',
 '19.6',
 '26.3',
 '11.2',
 '29.8',
 '41.0',
 '20.6',
 '7.2',
 '4.7',
 '14.4',
 '22.8',
 '97.0',
 '.454',
 '.358',
 '.745',
 '90.5',
 '.490',
 '13.7',
 '27.3',
 '.248',
 '106.2',
 '2004-05',
 'NBA',
 '26.9',
 '6-7',
 '220',
 '1230',
 '241.9',
 '35.9',
 '80.3',
 '5.6',
 '15.8',
 '19.7',
 '26.1',
 '12.0',
 '29.8',
 '41.9',
 '21.3',
 '7.5',
 '4.9',
 '14.5',
 '22.6',
 '97.2',
 '.447',
 '.356',
 '.756',
 '90.9',
 '.482',
 '13.6',
 '28.7',
 '.245',
 '106.1',
 '2003-04',
 'NBA',
 '27.0',
 '6-7',
 '219',
 '1189',
 '241.7',
 '35.0',
 '79.8',
 '5.2',
 '14.9',
 '18.2',
 '24.2',
 '12.1',
 '30.1',
 '42.2',
 '21.3',
 '7.9',
 '5.1',
 '15.0',
 '21.4',
 '93.4',
 '.439',
 '.347',
 '.752',
 '90.1',
 '.471',
 '14.2',
 '28.6',
 '.228',
 '102.9',
 '2002-03',
 'NBA',
 '27.2',
 '6-7',
 '219',
 '1189',
 '242.0',
 '35.7',
 '80.8',
 '5.1',
 '14.7',
 '18.5',
 '24.4',
 '12.0',
 '30.3',
 '42.3',
 '21.5',
 '7.9',
 '5.0',
 '14.9',
 '21.8',
 '95.1',
 '.442',
 '.349',
 '.758',
 '91.0',
 '.474',
 '14.0',
 '28.5',
 '.229',
 '103.6',
 '2001-02',
 'NBA',
 '27.4',
 '6-7',
 '218',
 '1189',
 '241.7',
 '36.2',
 '81.3',
 '5.2',
 '14.7',
 '17.9',
 '23.8',
 '12.2',
 '30.2',
 '42.4',
 '21.9',
 '7.8',
 '5.2',
 '14.5',
 '21.2',
 '95.5',
 '.445',
 '.354',
 '.752',
 '90.7',
 '.477',
 '13.6',
 '28.9',
 '.221',
 '104.5',
 '2000-01',
 'NBA',
 '27.7',
 '6-7',
 '216',
 '1189',
 '242.0',
 '35.7',
 '80.6',
 '4.8',
 '13.7',
 '18.6',
 '24.9',
 '12.0',
 '30.5',
 '42.5',
 '21.8',
 '7.8',
 '5.3',
 '15.0',
 '22.3',
 '94.8',
 '.443',
 '.354',
 '.748',
 '91.3',
 '.473',
 '14.1',
 '28.2',
 '.231',
 '103.0',
 '1999-00',
 'NBA',
 '27.8',
 '6-7',
 '216',
 '1189',
 '241.5',
 '36.8',
 '82.1',
 '4.8',
 '13.7',
 '19.0',
 '25.3',
 '12.4',
 '30.5',
 '42.9',
 '22.3',
 '7.9',
 '5.2',
 '15.5',
 '23.3',
 '97.5',
 '.449',
 '.353',
 '.750',
 '93.1',
 '.478',
 '14.2',
 '28.9',
 '.231',
 '104.1',
 '1998-99',
 'NBA',
 '27.9',
 '6-7',
 '215',
 '725',
 '241.8',
 '34.2',
 '78.2',
 '4.5',
 '13.2',
 '18.8',
 '25.8',
 '12.6',
 '29.1',
 '41.7',
 '20.7',
 '8.4',
 '5.0',
 '15.3',
 '22.2',
 '91.6',
 '.437',
 '.339',
 '.728',
 '88.9',
 '.466',
 '14.6',
 '30.2',
 '.240',
 '102.2',
 '1997-98',
 'NBA',
 '27.7',
 '6-7',
 '214',
 '1189',
 '241.9',
 '35.9',
 '79.7',
 '4.4',
 '12.7',
 '19.4',
 '26.3',
 '13.1',
 '28.5',
 '41.5',
 '22.0',
 '8.4',
 '5.1',
 '15.5',
 '22.4',
 '95.6',
 '.450',
 '.346',
 '.737',
 '90.3',
 '.478',
 '14.5',
 '31.4',
 '.243',
 '105.0',
 '1996-97',
 'NBA',
 '27.7',
 '6-7',
 '213',
 '1189',
 '241.9',
 '36.1',
 '79.3',
 '6.0',
 '16.8',
 '18.7',
 '25.3',
 '12.7',
 '28.4',
 '41.1',
 '22.0',
 '8.2',
 '4.9',
 '15.7',
 '22.1',
 '96.9',
 '.455',
 '.360',
 '.738',
 '90.1',
 '.493',
 '14.8',
 '30.8',
 '.236',
 '106.7',
 '1995-96',
 'NBA',
 '27.5',
 '6-7',
 '213',
 '1189',
 '241.6',
 '37.0',
 '80.2',
 '5.9',
 '16.0',
 '19.5',
 '26.4',
 '12.6',
 '28.6',
 '41.3',
 '22.7',
 '8.0',
 '5.1',
 '15.8',
 '23.0',
 '99.5',
 '.462',
 '.367',
 '.740',
 '91.8',
 '.499',
 '14.7',
 '30.6',
 '.243',
 '107.6',
 '1994-95',
 'NBA',
 '27.2',
 '6-7',
 '212',
 '1107',
 '241.9',
 '38.0',
 '81.5',
 '5.5',
 '15.3',
 '19.9',
 '27.1',
 '13.0',
 '28.5',
 '41.6',
 '23.4',
 '8.3',
 '5.2',
 '15.9',
 '23.5',
 '101.4',
 '.466',
 '.359',
 '.737',
 '92.9',
 '.500',
 '14.6',
 '31.4',
 '.245',
 '108.3',
 '1993-94',
 'NBA',
 '27.2',
 '6-7',
 '211',
 '1107',
 '241.1',
 '39.3',
 '84.4',
 '3.3',
 '9.9',
 '19.6',
 '26.6',
 '13.9',
 '29.1',
 '43.0',
 '24.4',
 '8.9',
 '5.2',
 '16.0',
 '22.2',
 '101.5',
 '.466',
 '.333',
 '.734',
 '95.1',
 '.485',
 '14.3',
 '32.2',
 '.232',
 '106.3',
 '1992-93',
 'NBA',
 '27.1',
 '6-7',
 '210',
 '1107',
 '241.7',
 '40.7',
 '86.0',
 '3.0',
 '9.0',
 '20.9',
 '27.7',
 '13.8',
 '29.3',
 '43.1',
 '24.7',
 '8.6',
 '5.2',
 '15.9',
 '23.2',
 '105.3',
 '.473',
 '.336',
 '.754',
 '96.8',
 '.491',
 '14.0',
 '32.0',
 '.243',
 '108.0',
 '1991-92',
 'NBA',
 '27.2',
 '6-7',
 '208',
 '1107',
 '241.8',
 '41.3',
 '87.3',
 '2.5',
 '7.6',
 '20.2',
 '26.7',
 '14.4',
 '29.3',
 '43.7',
 '24.5',
 '8.6',
 '5.5',
 '15.6',
 '22.2',
 '105.3',
 '.472',
 '.331',
 '.759',
 '96.6',
 '.487',
 '13.6',
 '32.9',
 '.232',
 '108.2',
 '1990-91',
 'NBA',
 '27.2',
 '6-7',
 '209',
 '1107',
 '241.8',
 '41.4',
 '87.2',
 '2.3',
 '7.1',
 '21.3',
 '27.9',
 '14.0',
 '29.3',
 '43.3',
 '24.7',
 '8.6',
 '5.3',
 '16.0',
 '23.2',
 '106.3',
 '.474',
 '.320',
 '.765',
 '97.8',
 '.487',
 '13.9',
 '32.3',
 '.245',
 '107.9',
 '1989-90',
 'NBA',
 '27.1',
 '6-7',
 '208',
 '1107',
 '241.5',
 '41.5',
 '87.2',
 '2.2',
 '6.6',
 '21.8',
 '28.5',
 '13.8',
 '29.3',
 '43.1',
 '24.9',
 '8.5',
 '5.1',
 '16.1',
 '23.3',
 '107.0',
 '.476',
 '.331',
 '.764',
 '98.3',
 '.489',
 '13.9',
 '32.1',
 '.250',
 '108.1',
 '1988-89',
 'NBA',
 '26.9',
 '6-7',
 '208',
 '1025',
 '241.5',
 '42.5',
 '89.0',
 '2.1',
 '6.6',
 '22.1',
 '28.8',
 '14.5',
 '29.4',
 '43.9',
 '25.6',
 '9.1',
 '5.3',
 '17.2',
 '23.7',
 '109.2',
 '.477',
 '.323',
 '.768',
 '100.6',
 '.489',
 '14.5',
 '33.0',
 '.249',
 '107.8',
 '1987-88',
 'NBA',
 '26.9',
 '6-7',
 '209',
 '943',
 '241.3',
 '42.1',
 ...]

In [12]:
ncols = len(headers)
nrows = int(len(data)/ncols)

In [13]:
seasons = pd.DataFrame(np.array(data).reshape((nrows, ncols)), columns=headers)

In [14]:
#full table from basketball reference, stats are per game
pd.set_option('max_columns', 32)
seasons.head(10)

,Season,Lg,Age,Ht,Wt,G,MP,FG,FGA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,FG%,3P%,FT%,Pace,eFG%,TOV%,ORB%,FT/FGA,ORtg
0,2019-20,NBA,26.0,6-6,216,971,241.7,40.8,88.8,12.1,33.9,17.7,22.9,10.1,34.7,44.9,24.3,7.7,4.9,14.5,20.6,111.4,.460,.357,.771,100.2,.528,12.8,22.6,.199,110.4
1,2018-19,NBA,26.3,6-6,217,1230,241.6,41.1,89.2,11.4,32.0,17.7,23.1,10.3,34.8,45.2,24.6,7.6,5.0,14.1,20.9,111.2,.461,.355,.766,100.0,.524,12.4,22.9,.198,110.4
2,2017-18,NBA,26.4,6-7,219,1230,241.4,39.6,86.1,10.5,29.0,16.6,21.7,9.7,33.8,43.5,23.2,7.7,4.8,14.3,19.9,106.3,.460,.362,.767,97.3,.521,13.0,22.3,.193,108.6
3,2016-17,NBA,26.6,6-7,220,1230,241.6,39.0,85.4,9.7,27.0,17.8,23.1,10.1,33.4,43.5,22.6,7.7,4.7,14.0,19.9,105.6,.457,.358,.772,96.4,.514,12.7,23.3,.209,108.8
4,2015-16,NBA,26.7,6-7,221,1230,241.8,38.2,84.6,8.5,24.1,17.7,23.4,10.4,33.3,43.8,22.3,7.8,5.0,14.4,20.3,102.7,.452,.354,.757,95.8,.502,13.2,23.8,.209,106.4
5,2014-15,NBA,26.7,6-7,222,1230,242.0,37.5,83.6,7.8,22.4,17.1,22.8,10.9,32.4,43.3,22.0,7.7,4.8,14.4,20.2,100.0,.449,.350,.750,93.9,.496,13.3,25.1,.205,105.6
6,2013-14,NBA,26.5,6-7,223,1230,242.0,37.7,83.0,7.7,21.5,17.8,23.6,10.9,31.8,42.7,22.0,7.7,4.7,14.6,20.7,101.0,.454,.360,.756,93.9,.501,13.6,25.5,.215,106.6
7,2012-13,NBA,26.7,6-7,223,1229,241.9,37.1,82.0,7.2,20.0,16.7,22.2,11.2,31.0,42.1,22.1,7.8,5.1,14.6,19.8,98.1,.453,.359,.753,92.0,.496,13.7,26.5,.204,105.8
8,2011-12,NBA,26.6,6-7,223,990,241.9,36.5,81.4,6.4,18.4,16.9,22.5,11.4,30.8,42.2,21.0,7.7,5.1,14.6,19.6,96.3,.448,.349,.752,91.3,.487,13.8,27.0,.208,104.6
9,2010-11,NBA,26.6,6-7,223,1230,241.9,37.2,81.2,6.5,18.0,18.6,24.4,10.9,30.5,41.4,21.5,7.3,4.9,14.3,20.7,99.6,.459,.358,.763,92.1,.498,13.4,26.4,.229,107.3

### NBA Stats per players (API)

#### All players database

In [15]:
response=requests.get("https://www.balldontlie.io/api/v1/players?per_page=100&page=1")
response

In [16]:
pagesrange=range(1,34)

In [18]:
# full table of all players from balldontlie API
players = pd.DataFrame()
for i in pagesrange:
    playerpage=pd.DataFrame(requests.get(f"https://www.balldontlie.io/api/v1/players?per_page=100&page={i}").json()["data"])
    players=pd.concat([players,playerpage])
players.head()

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds
0,14,Ike,NaN,NaN,Anigbogu,C,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
1,25,Ron,NaN,NaN,Baker,G,"{'id': 20, 'abbreviation': 'NYK', 'city': 'New...",NaN
2,47,Jabari,NaN,NaN,Bird,G,"{'id': 2, 'abbreviation': 'BOS', 'city': 'Bost...",NaN
3,67,MarShon,NaN,NaN,Brooks,G,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
4,71,Lorenzo,NaN,NaN,Brown,G,"{'id': 28, 'abbreviation': 'TOR', 'city': 'Tor...",NaN

In [30]:
players.loc[players["last_name"]=="Carter",:]

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds
53,1224,Anthony,NaN,NaN,Carter,,"{'id': 16, 'abbreviation': 'MIA', 'city': 'Mia...",NaN
51,1523,Maurice,NaN,NaN,Carter,,"{'id': 14, 'abbreviation': 'LAL', 'city': 'Los...",NaN
59,2469,Ron,NaN,NaN,Carter,,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
20,2530,Reggie,NaN,NaN,Carter,,"{'id': 20, 'abbreviation': 'NYK', 'city': 'New...",NaN
21,2531,Butch,NaN,NaN,Carter,,"{'id': 14, 'abbreviation': 'LAL', 'city': 'Los...",NaN
46,2656,Howard,NaN,NaN,Carter,,"{'id': 8, 'abbreviation': 'DEN', 'city': 'Denv...",NaN
36,87,Jevon,6.0,2.0,Carter,G,"{'id': 24, 'abbreviation': 'PHX', 'city': 'Pho...",196.0
37,88,Vince,6.0,6.0,Carter,F-G,"{'id': 1, 'abbreviation': 'ATL', 'city': 'Atla...",220.0

In [20]:
players.shape

(3268, 8)

#### Seasons Average database

In [21]:
response = requests.get("https://www.balldontlie.io/api/v1/season_averages?season=1979&player_ids[]=577")
response.json()

{'data': []}

In [31]:
seasons_range=list(range(2010,2019))
seasons_range

[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

In [23]:
playersidrange = list(players["id"].unique())
len(playersidrange)

3268

In [24]:
playerseason=pd.DataFrame(requests.get(f"https://www.balldontlie.io/api/v1/season_averages?player_ids[]=115&season=2016").json()["data"])
playerseason

,games_played,player_id,season,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,reb,ast,stl,blk,turnover,pf,pts,fg_pct,fg3_pct,ft_pct
0,79,115,2016,33:23,8.54,18.27,4.1,9.99,4.11,4.58,0.77,3.7,4.47,6.63,1.8,0.22,3.03,2.32,25.3,0.468,0.411,0.898

In [ ]:
players_season_average_2010s = pd.DataFrame()
for s in seasons_range:
    for f in tqdm(playersidrange):
        try:
            playerseason=pd.DataFrame(requests.get(f"https://www.balldontlie.io/api/v1/season_averages?season={s}&player_ids[]={f}").json()["data"])
            players_season_average_2010s=pd.concat([players_season_average_2010s,playerseason])
        except:
            pass
players_season_average_2010s.head()

HBox(children=(IntProgress(value=0, max=3268), HTML(value='')))

From cffi callback <function _verify_callback at 0x0000024DCF95AAF8>:
Traceback (most recent call last):
  File "C:\Users\Pedro\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 306, in wrapper
    @wraps(callback)
KeyboardInterrupt
From cffi callback <function _verify_callback at 0x0000024DCF099798>:
Traceback (most recent call last):
  File "C:\Users\Pedro\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 306, in wrapper
    @wraps(callback)
KeyboardInterrupt
From cffi callback <function _verify_callback at 0x0000024DCDF543A8>:
Traceback (most recent call last):
  File "C:\Users\Pedro\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 306, in wrapper
    @wraps(callback)
KeyboardInterrupt

## Data Cleaning and Manipulation

### NBA Stats per Season

In [139]:
seasons_3 = seasons.loc[:,["Season","3P","3PA","PTS","3P%"]]
seasons_3

     Season    3P   3PA    PTS   3P%
0   2019-20  12.1  33.9  111.4  .357
1   2018-19  11.4  32.0  111.2  .355
2   2017-18  10.5  29.0  106.3  .362
3   2016-17   9.7  27.0  105.6  .358
4   2015-16   8.5  24.1  102.7  .354
..      ...   ...   ...    ...   ...
69  1950-51               84.1
70  1949-50               80.0
71  1948-49               80.0
72  1947-48               72.7
73  1946-47               67.8

[74 rows x 5 columns]

In [140]:
seasons_3.dtypes

Season    object
3P        object
3PA       object
PTS       object
3P%       object
dtype: object

In [141]:
#replacing empty values for nan
seasons_3=seasons_3.replace(r'^\s*$', np.nan, regex=True)

In [142]:
seasons_3["Season"]=seasons_3.loc[:,"Season"].apply(lambda x: x[0:4])

In [143]:
seasons_3["Season"]=seasons_3["Season"].astype(int)
seasons_3["3P"]=seasons_3["3P"].astype(float)
seasons_3["3PA"]=seasons_3["3PA"].astype(float)
seasons_3["PTS"]=seasons_3["PTS"].astype(float)
seasons_3["3P%"]=seasons_3["3P%"].astype(float)

In [144]:
seasons_3.dtypes

Season      int32
3P        float64
3PA       float64
PTS       float64
3P%       float64
dtype: object

In [145]:
seasons_3 = seasons_3.dropna(subset=["3P"])

In [146]:
seasons_3 = seasons_3.rename(columns={"3P%":"3P_pct"})

In [148]:
seasons_3=seasons_3.sort_values(by="Season")

In [149]:
#Pct_change_3P calculates the increase in 3Ps from an year to another
#3P%_in_PTS calculates the importance of 3Ps in PTS made
seasons_3["Pct_change_3P"]=seasons_3["3P"].pct_change()
seasons_3["3P_pct_in_PTS"]=(seasons_3["3P"]*3)/seasons_3["PTS"]

In [150]:
seasons_3

    Season    3P   3PA    PTS  3P_pct  Pct_change_3P  3P_pct_in_PTS
40    1979   0.8   2.8  109.3   0.280            NaN       0.021958
39    1980   0.5   2.0  108.1   0.245      -0.375000       0.013876
38    1981   0.6   2.3  108.6   0.262       0.200000       0.016575
37    1982   0.5   2.3  108.5   0.238      -0.166667       0.013825
36    1983   0.6   2.4  110.1   0.250       0.200000       0.016349
35    1984   0.9   3.1  110.8   0.282       0.500000       0.024368
34    1985   0.9   3.3  110.2   0.282       0.000000       0.024501
33    1986   1.4   4.7  109.9   0.301       0.555556       0.038217
32    1987   1.6   5.0  108.2   0.316       0.142857       0.044362
31    1988   2.1   6.6  109.2   0.323       0.312500       0.057692
30    1989   2.2   6.6  107.0   0.331       0.047619       0.061682
29    1990   2.3   7.1  106.3   0.320       0.045455       0.064911
28    1991   2.5   7.6  105.3   0.331       0.086957       0.071225
27    1992   3.0   9.0  105.3   0.336       0.200000       0.085470
26    1993   3.3   9.9  101.5   0.333       0.100000       0.097537
25    1994   5.5  15.3  101.4   0.359       0.666667       0.162722
24    1995   5.9  16.0   99.5   0.367       0.072727       0.177889
23    1996   6.0  16.8   96.9   0.360       0.016949       0.185759
22    1997   4.4  12.7   95.6   0.346      -0.266667       0.138075
21    1998   4.5  13.2   91.6   0.339       0.022727       0.147380
20    1999   4.8  13.7   97.5   0.353       0.066667       0.147692
19    2000   4.8  13.7   94.8   0.354       0.000000       0.151899
18    2001   5.2  14.7   95.5   0.354       0.083333       0.163351
17    2002   5.1  14.7   95.1   0.349      -0.019231       0.160883
16    2003   5.2  14.9   93.4   0.347       0.019608       0.167024
15    2004   5.6  15.8   97.2   0.356       0.076923       0.172840
14    2005   5.7  16.0   97.0   0.358       0.017857       0.176289
13    2006   6.1  16.9   98.7   0.358       0.070175       0.185410
12    2007   6.6  18.1   99.9   0.362       0.081967       0.198198
11    2008   6.6  18.1  100.0   0.367       0.000000       0.198000
10    2009   6.4  18.1  100.4   0.355      -0.030303       0.191235
9     2010   6.5  18.0   99.6   0.358       0.015625       0.195783
8     2011   6.4  18.4   96.3   0.349      -0.015385       0.199377
7     2012   7.2  20.0   98.1   0.359       0.125000       0.220183
6     2013   7.7  21.5  101.0   0.360       0.069444       0.228713
5     2014   7.8  22.4  100.0   0.350       0.012987       0.234000
4     2015   8.5  24.1  102.7   0.354       0.089744       0.248296
3     2016   9.7  27.0  105.6   0.358       0.141176       0.275568
2     2017  10.5  29.0  106.3   0.362       0.082474       0.296331
1     2018  11.4  32.0  111.2   0.355       0.085714       0.307554
0     2019  12.1  33.9  111.4   0.357       0.061404       0.325853

### NBA Stats per players

In [160]:
players = players.loc[:,["id","first_name","last_name"]]

   id first_name last_name
0  14        Ike  Anigbogu
1  25        Ron     Baker
2  47     Jabari      Bird
3  67    MarShon    Brooks
4  71    Lorenzo     Brown

In [165]:
players = players.rename(columns={"id":"player_id"})
players.head(5)

   player_id first_name last_name
0         14        Ike  Anigbogu
1         25        Ron     Baker
2         47     Jabari      Bird
3         67    MarShon    Brooks
4         71    Lorenzo     Brown

In [231]:
players_season_average_1516 = pd.concat([players_season_average_2015,players_season_average_2016],ignore_index=True)

In [232]:
players_season_average_1516

,games_played,player_id,season,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,reb,ast,stl,blk,turnover,pf,pts,fg_pct,fg3_pct,ft_pct
0,8,71,2015,7:35,1.00,3.13,0.13,1.00,0.38,0.50,0.00,0.88,0.88,1.38,0.38,0.13,1.13,0.50,2.50,0.320,0.125,0.750
1,69,90,2015,27:15,4.33,9.01,1.62,3.97,1.49,2.30,0.84,5.10,5.94,1.38,0.81,0.25,1.36,2.23,11.78,0.481,0.409,0.648
2,75,179,2015,30:04,5.77,10.19,0.00,0.01,1.95,2.76,2.96,6.92,9.88,1.41,0.63,1.28,1.61,2.57,13.49,0.567,0.000,0.705
3,70,1593,2015,20:43,2.50,3.99,0.01,0.01,0.34,0.71,1.73,5.30,7.03,2.31,0.47,1.63,1.19,3.16,5.36,0.627,1.000,0.480
4,79,241,2015,22:47,3.15,5.39,0.13,0.54,0.87,1.53,2.25,4.14,6.39,1.75,0.66,1.05,1.19,2.71,7.30,0.585,0.233,0.570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,80,212,2016,29:40,2.29,5.98,1.18,3.38,1.29,1.60,0.64,3.20,3.84,1.76,0.90,0.40,1.03,2.28,7.04,0.383,0.348,0.805
680,67,214,2016,32:41,6.04,13.33,1.49,4.19,1.78,2.51,0.69,3.25,3.94,7.28,1.49,0.66,2.90,1.99,15.36,0.454,0.356,0.708
681,82,215,2016,19:59,2.84,6.56,1.18,3.33,0.80,0.98,0.33,2.41,2.74,1.24,0.79,0.38,0.80,1.33,7.67,0.433,0.355,0.825
682,78,216,2016,22:34,3.01,6.95,0.19,0.86,2.44,3.24,1.23,4.56,5.79,1.97,1.05,0.56,1.49,2.27,8.65,0.434,0.224,0.751
683,79,115,2016,33:23,8.54,18.27,4.10,9.99,4.11,4.58,0.77,3.70,4.47,6.63,1.80,0.22,3.03,2.32,25.30,0.468,0.411,0.898

In [233]:
players_season_average_1516=players_season_average_1516.loc[:,["games_played","player_id","season","fg3m","fg3a","fg3_pct","pts"]].reset_index(drop=True)

In [234]:
players_season_average_1516

     games_played  player_id  season  fg3m  fg3a  fg3_pct    pts
0               8         71    2015  0.13  1.00    0.125   2.50
1              69         90    2015  1.62  3.97    0.409  11.78
2              75        179    2015  0.00  0.01    0.000  13.49
3              70       1593    2015  0.01  0.01    1.000   5.36
4              79        241    2015  0.13  0.54    0.233   7.30
..            ...        ...     ...   ...   ...      ...    ...
679            80        212    2016  1.18  3.38    0.348   7.04
680            67        214    2016  1.49  4.19    0.356  15.36
681            82        215    2016  1.18  3.33    0.355   7.67
682            78        216    2016  0.19  0.86    0.224   8.65
683            79        115    2016  4.10  9.99    0.411  25.30

[684 rows x 7 columns]

## Data Storage

In [97]:
load_dotenv("./.env")

True

In [98]:
server = 'postgresql'
username = 'postgres'
password = os.getenv("password")
ip = 'localhost'
database = 'nba3pts'

# create the engine
engine = db.create_engine(f'{server}://{username}:{password}@{ip}/{database}')

# open the connection
conn = engine.connect()

In [235]:
players_season_average_1516.to_sql('players_season_average_1516', con=conn, if_exists='replace', index=False)

In [166]:
players.to_sql('players', con=conn, if_exists='replace', index=False)

In [151]:
seasons_3.to_sql('seasons_3', con=conn, if_exists='replace', index=False)